//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.ChequeInfoes = new HashSet<ChequeInfo>();
            this.JournalDetails = new HashSet<JournalDetail>();
            this.JournalDetails1 = new HashSet<JournalDetail>();
            this.OpeningStocks = new HashSet<OpeningStock>();
            this.PurchaseHeads = new HashSet<PurchaseHead>();
            this.StockSerials = new HashSet<StockSerial>();
        }
    
        public int AccountId { get; set; }
        public Nullable<int> MainHeadId { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Note { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string SecCode { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual MainHead MainHead { get; set; }
        public virtual Market Market { get; set; }
        public virtual ICollection<ChequeInfo> ChequeInfoes { get; set; }
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
        public virtual ICollection<JournalDetail> JournalDetails1 { get; set; }
        public virtual ICollection<OpeningStock> OpeningStocks { get; set; }
        public virtual ICollection<PurchaseHead> PurchaseHeads { get; set; }
        public virtual ICollection<StockSerial> StockSerials { get; set; }
    }
}
