//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Branches = new HashSet<Branch>();
            this.Customers = new HashSet<Customer>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> ThanaId { get; set; }
    
        public virtual Thana Thana { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
