//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.CCLimits = new HashSet<CCLimit>();
            this.ChequeInfoes = new HashSet<ChequeInfo>();
            this.PurchaseHeads = new HashSet<PurchaseHead>();
        }
    
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> Opening { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual ICollection<CCLimit> CCLimits { get; set; }
        public virtual ICollection<ChequeInfo> ChequeInfoes { get; set; }
        public virtual ICollection<PurchaseHead> PurchaseHeads { get; set; }
    }
}
