//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Accounts = new HashSet<Account>();
            this.Banks = new HashSet<Bank>();
            this.CCLimits = new HashSet<CCLimit>();
            this.ChequeInfoes = new HashSet<ChequeInfo>();
            this.Customers = new HashSet<Customer>();
            this.Employees = new HashSet<Employee>();
            this.Items = new HashSet<Item>();
            this.ItemJournals = new HashSet<ItemJournal>();
            this.JournalDetails = new HashSet<JournalDetail>();
            this.MainHeads = new HashSet<MainHead>();
            this.Markets = new HashSet<Market>();
            this.Models = new HashSet<Model>();
            this.OpeningStocks = new HashSet<OpeningStock>();
            this.PurchaseHeads = new HashSet<PurchaseHead>();
            this.ReceivePayments = new HashSet<ReceivePayment>();
            this.Sections = new HashSet<Section>();
            this.StockOpenings = new HashSet<StockOpening>();
            this.StockSerials = new HashSet<StockSerial>();
            this.Suppliers = new HashSet<Supplier>();
            this.Units = new HashSet<Unit>();
            this.VoucherInfoes = new HashSet<VoucherInfo>();
        }
    
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Area Area { get; set; }
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<CCLimit> CCLimits { get; set; }
        public virtual ICollection<ChequeInfo> ChequeInfoes { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ItemJournal> ItemJournals { get; set; }
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
        public virtual ICollection<MainHead> MainHeads { get; set; }
        public virtual ICollection<Market> Markets { get; set; }
        public virtual ICollection<Model> Models { get; set; }
        public virtual ICollection<OpeningStock> OpeningStocks { get; set; }
        public virtual ICollection<PurchaseHead> PurchaseHeads { get; set; }
        public virtual ICollection<ReceivePayment> ReceivePayments { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<StockOpening> StockOpenings { get; set; }
        public virtual ICollection<StockSerial> StockSerials { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
        public virtual ICollection<VoucherInfo> VoucherInfoes { get; set; }
    }
}
