//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeInfo
    {
        public int ChequeInfoId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<System.DateTime> ChequeMDate { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> CustomerBankId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ChequeType { get; set; }
        public string FinalStatus { get; set; }
        public string Bounched { get; set; }
        public Nullable<System.DateTime> BounchedDate { get; set; }
        public string ReIssue { get; set; }
        public Nullable<System.DateTime> ReIssueDate { get; set; }
        public string CashPayStart { get; set; }
        public string ChequeCancel { get; set; }
        public Nullable<System.DateTime> ChequeCancelDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> RPId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CustomerBank CustomerBank { get; set; }
        public virtual PurchaseHead PurchaseHead { get; set; }
        public virtual ReceivePayment ReceivePayment { get; set; }
    }
}
