//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Telephone { get; set; }
        public string OwnerName { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> AcountId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> Active { get; set; }
        public string ImagePath { get; set; }
        public string NID { get; set; }
        public string TradeLicense { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Address { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CustomerBank CustomerBank { get; set; }
        public virtual Market Market { get; set; }
    }
}
