//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MoterName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string NationalId { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Education { get; set; }
        public string Address { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string BloodGroup { get; set; }
        public string Reference { get; set; }
        public string ParmanentAddress { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public string ResignationType { get; set; }
        public string Status { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
