//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemJournal
    {
        public int ProductJournalId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> OutQty { get; set; }
        public Nullable<decimal> UnitPrce { get; set; }
        public string Type { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
