//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public int JournalDetailId { get; set; }
        public string JournalNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string ChecqueNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<System.DateTime> ChequeMDate { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public Nullable<int> TransAccountId { get; set; }
        public Nullable<int> RPID { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Market Market { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PurchaseHead PurchaseHead { get; set; }
    }
}
