//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public Market()
        {
            this.Accounts = new HashSet<Account>();
            this.Customers = new HashSet<Customer>();
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public int MarketId { get; set; }
        public string MarketName { get; set; }
        public string Contact { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
    }
}
