//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.OpeningStocks = new HashSet<OpeningStock>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.StockSerials = new HashSet<StockSerial>();
        }
    
        public int ModelId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ModelName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> ReorderQty { get; set; }
        public Nullable<int> IsWarranty { get; set; }
        public Nullable<int> AvgCost { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<OpeningStock> OpeningStocks { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual ICollection<StockSerial> StockSerials { get; set; }
    }
}
