//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMode
    {
        public PaymentMode()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
            this.PurchaseHeads = new HashSet<PurchaseHead>();
            this.ReceivePayments = new HashSet<ReceivePayment>();
        }
    
        public int PaymentModeId { get; set; }
        public string PaymentType { get; set; }
    
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
        public virtual ICollection<PurchaseHead> PurchaseHeads { get; set; }
        public virtual ICollection<ReceivePayment> ReceivePayments { get; set; }
    }
}
