//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
