//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int PurchaseDetailId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitPice { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> SerialId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Model Model { get; set; }
        public virtual PurchaseHead PurchaseHead { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual StockSerial StockSerial { get; set; }
    }
}
