//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSerial
    {
        public StockSerial()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int SerialId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string SerialNo { get; set; }
        public string OnHand { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Model Model { get; set; }
        public virtual PurchaseHead PurchaseHead { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
