//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.PurchaseHeads = new HashSet<PurchaseHead>();
        }
    
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string OwnerName { get; set; }
        public string SupplierCode { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<PurchaseHead> PurchaseHeads { get; set; }
    }
}
