//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvincialEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thana
    {
        public Thana()
        {
            this.Areas = new HashSet<Area>();
        }
    
        public int ThanaId { get; set; }
        public string ThanaName { get; set; }
        public Nullable<int> DistrictId { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual District District { get; set; }
    }
}
